platform: linux
inputs:
  - name: terraform
  - name: gpdb_src
  - name: bin_gpdb
  - name: bin_gpdb_clients_windows_rc
run:
  path: "sh"
  args:
  - -c
  - |
    set -euxo pipefail
    exit 1
params:
  REMOTE_PORT:
  REMOTE_USER:
  REMOTE_KEY: